const fs = require('fs');
const path = require('path');

const vocabFilePath = path.join(__dirname, 'maritime_vocab.json');

function expandVocabulary() {
  console.log("Reading existing vocabulary...");
  let vocab = [];
  if (fs.existsSync(vocabFilePath)) {
    vocab = JSON.parse(fs.readFileSync(vocabFilePath, 'utf8'));
  }

  console.log(`Current vocabulary count: ${vocab.length}`);

  const generatedVocab = [];

  // 1. Manual Daily Conversation Phrases (162 items)
  const manualPhrases = [
    ["Good morning", "A standard greeting used before noon.", "Good morning, Captain.", "สวัสดีตอนเช้า", "คำทักทายตอนเช้า"],
    ["Good afternoon", "A standard greeting used after noon until evening.", "Good afternoon, Chief.", "สวัสดีตอนบ่าย", "คำทักทายตอนบ่าย"],
    ["Good evening", "A standard greeting used in the evening.", "Good evening, Officer.", "สวัสดีตอนเย็น", "คำทักทายตอนเย็น"],
    ["How are you?", "A polite inquiry about someone's well-being.", "How are you today?", "คุณสบายดีไหม", "การถามไถ่สารทุกข์สุกดิบ"],
    ["I am fine", "A standard response indicating good well-being.", "I am fine, thank you.", "ฉันสบายดี", "การตอบรับว่าสบายดี"],
    ["Please repeat", "A request to say something again.", "Please repeat the last message.", "กรุณาพูดซ้ำ", "ขอให้พูดซ้ำอีกครั้ง"],
    ["I do not understand", "An expression of confusion or inability to comprehend.", "I do not understand the instruction.", "ฉันไม่เข้าใจ", "แสดงความไม่เข้าใจ"],
    ["Message received", "Acknowledgment that a message has been heard and understood.", "Message received, loud and clear.", "รับทราบข้อความ", "ยืนยันการรับข้อความ"],
    ["Loud and clear", "Confirmation that a radio transmission is perfectly audible.", "I read you loud and clear.", "ชัดเจนดีมาก", "สัญญาณเสียงชัดเจน"],
    ["Radio check", "A request to verify if the radio is transmitting and receiving properly.", "Bridge, this is engine room, radio check.", "ทดสอบวิทยุ", "การทดสอบการสื่อสารทางวิทยุ"],
    ["Do you read me?", "Asking if the listener can hear the transmission.", "Deck, do you read me?", "คุณได้ยินฉันไหม", "ถามว่าได้ยินข้อความหรือไม่"],
    ["Over and out", "Indicates the end of a transmission and no reply is expected.", "Task completed. Over and out.", "จบการสนทนา", "สิ้นสุดการสื่อสารและไม่ต้องการการตอบกลับ"],
    ["Roger that", "A standard radio response meaning 'I understand'.", "Roger that, proceeding to the station.", "รับทราบ", "รับทราบข้อความหรือคำสั่ง"],
    ["Say again", "Standard marine phrase requesting the sender to repeat the message.", "Say again your ETA.", "พูดอีกครั้ง", "ขอให้ผู้ส่งทวนข้อความอีกครั้ง"],
    ["Speak slower", "A request for the speaker to reduce their speaking speed.", "Please speak slower, interference is high.", "พูดช้าลงหน่อย", "ขอให้พูดช้าลง"],
    ["Permission to board", "A formal request to come onto the ship.", "Captain, permission to board?", "ขออนุญาตขึ้นเรือ", "การขออนุญาตขึ้นบนเรือ"],
    ["Permission granted", "Formal approval to proceed with a requested action.", "Permission granted, proceed via gangway.", "อนุญาต", "การอนุมัติให้ดำเนินการได้"],
    ["Permission denied", "Formal refusal of a requested action.", "Permission denied, standby.", "ไม่อนุญาต", "การปฏิเสธคำขอ"],
    ["Report your position", "A command to state current coordinates or location.", "Tug boat, report your position.", "รายงานตำแหน่งของคุณ", "คำสั่งให้บอกตำแหน่งปัจจุบัน"],
    ["What are your intentions?", "Asking another vessel or person what they plan to do.", "Approaching vessel, what are your intentions?", "คุณมีความตั้งใจจะทำอะไร", "ถามถึงแผนการหรือการกระทำต่อไป"],
    ["Keep clear", "A warning to stay away from a specific area or vessel.", "Keep clear of the mooring lines.", "อยู่ให้ห่าง", "คำเตือนให้อยู่ห่างจากพื้นที่"],
    ["I require assistance", "A formal statement asking for help.", "I require assistance with the heavy cargo.", "ฉันต้องการความช่วยเหลือ", "การขอความช่วยเหลือ"],
    ["Medical emergency", "A statement indicating someone needs immediate medical attention.", "We have a medical emergency in the galley.", "เหตุฉุกเฉินทางการแพทย์", "เหตุฉุกเฉินที่ต้องการแพทย์ด่วน"],
    ["Fire on board", "The standard phrase to report a fire.", "Fire on board, engine room level 2.", "ไฟไหม้บนเรือ", "การแจ้งเหตุเพลิงไหม้บนเรือ"],
    ["Man overboard", "The standard alarm phrase when someone falls into the sea.", "Man overboard, port side!", "คนตกน้ำ", "สัญญาณเตือนเมื่อมีคนตกน้ำ"],
    ["Abandon ship", "The ultimate command to evacuate the vessel.", "This is the Captain, abandon ship!", "สละเรือ", "คำสั่งให้อพยพออกจากเรือ"],
    ["Muster all crew", "Command to assemble everyone at the designated stations.", "Muster all crew at the lifeboat stations.", "รวมพลลูกเรือทั้งหมด", "คำสั่งให้ลูกเรือไปที่จุดรวมพล"],
    ["Is everyone accounted for?", "Asking if all personnel have been checked and are present.", "Is everyone accounted for at station A?", "ทุกคนอยู่ครบไหม", "ถามว่าเช็คชื่อครบหรือยัง"],
    ["Someone is missing", "Report that a person is not at their muster station.", "Someone is missing from the engine department.", "มีคนหายไป", "รายงานว่ามีคนไม่มาตามจุดนัดหมาย"],
    ["Launch lifeboats", "Command to deploy the survival craft.", "Launch lifeboats immediately.", "ปล่อยเรือชูชีพ", "คำสั่งให้ปล่อยเรือชูชีพลงน้ำ"],
    ["Prepare the gangway", "Order to get the boarding ramp ready for use.", "Prepare the gangway for the pilot.", "เตรียมสะพานเดินเรือ", "คำสั่งให้เตรียมบันไดขึ้นลงเรือ"],
    ["Heave in the line", "Command to pull a rope or cable aboard.", "Heave in the line on the forward winch.", "ดึงเชือกเข้ามา", "คำสั่งให้สาวหรือกว้านเชือกเข้าเรือ"],
    ["Slack the line", "Command to release tension on a rope.", "Slack the line to let the tug move.", "หย่อนเชือก", "คำสั่งให้คลายความตึงของเชือก"],
    ["Make it fast", "Command to secure a line firmly.", "Make it fast on the forward bollard.", "ผูกให้แน่น", "คำสั่งให้ยึดหรือผูกเชือกให้แน่น"],
    ["Let go all lines", "Command to release the ship from the dock.", "Let go all lines, we are departing.", "ปลดเชือกทั้งหมด", "คำสั่งให้ปลดเชือกผูกเรือทั้งหมด"],
    ["What is the draft?", "Asking for the depth of the submerged part of the ship.", "What is the draft forward?", "อัตรากินน้ำลึกเท่าไหร่", "ถามระดับความลึกของเรือ"],
    ["Check the sounding", "Order to measure the depth of liquid in a tank.", "Check the sounding of ballast tank 3.", "ตรวจสอบระดับน้ำ/น้ำมัน", "คำสั่งให้วัดระดับของเหลวในถัง"],
    ["Open the valve", "Command to allow flow through a pipe.", "Open the valve for the port manifold.", "เปิดวาล์ว", "คำสั่งให้เปิดท่อหรือวาล์ว"],
    ["Close the valve", "Command to stop flow through a pipe.", "Close the valve to stop the fuel transfer.", "ปิดวาล์ว", "คำสั่งให้ปิดท่อหรือวาล์ว"],
    ["Check the pressure", "Order to verify the reading on a pressure gauge.", "Check the pressure on the main boiler.", "ตรวจสอบแรงดัน", "คำสั่งให้ดูค่าความดัน"],
    ["Check the temperature", "Order to verify the heat level of a system.", "Check the temperature of the exhaust gas.", "ตรวจสอบอุณหภูมิ", "คำสั่งให้ดูค่าความร้อน"],
    ["Top up the oil", "Command to add lubricating oil to the required level.", "Top up the oil in the steering gear.", "เติมน้ำมันให้เต็ม", "คำสั่งให้เติมน้ำมันหล่อลื่นให้ได้ระดับ"],
    ["Clean the filter", "Command to remove debris from a strainer or filter.", "Clean the filter on the seawater intake.", "ทำความสะอาดตัวกรอง", "คำสั่งให้ล้างไส้กรอง"],
    ["Replace the filter", "Command to install a new filter element.", "Replace the filter for the air conditioning.", "เปลี่ยนตัวกรอง", "คำสั่งให้เปลี่ยนไส้กรองใหม่"],
    ["Switch to manual", "Command to change from automatic to human control.", "Switch to manual steering now.", "เปลี่ยนเป็นระบบแมนนวล", "สั่งให้ควบคุมด้วยมือแทนระบบอัตโนมัติ"],
    ["What is the weather forecast?", "Asking for the predicted meteorological conditions.", "What is the weather forecast for tomorrow?", "พยากรณ์อากาศเป็นอย่างไร", "ถามสภาพอากาศล่วงหน้า"],
    ["Visibility is poor", "Statement that it is difficult to see far.", "Visibility is poor due to heavy fog.", "ทัศนวิสัยแย่", "การมองเห็นไม่ชัดเจน"],
    ["Prepare for heavy weather", "Command to secure the ship for rough seas.", "Prepare for heavy weather, secure all loose gear.", "เตรียมรับมือสภาพอากาศเลวร้าย", "คำสั่งให้จัดเก็บของเตรียมเจอพายุ"],
    ["Hand over the watch", "The process of transferring duty to the next shift.", "Hand over the watch to the second officer.", "ส่งมอบเวร", "การส่งต่อหน้าที่ยามเรือเรือ"],
    ["Watch your step", "A warning to be careful where you walk.", "Watch your step on the slippery deck.", "ระวังทางเดิน", "คำเตือนให้ระวังลื่นหรือสะดุด"],
    ["Wear your PPE", "Command to put on Personal Protective Equipment.", "Wear your PPE before entering the hold.", "สวมอุปกรณ์ป้องกันอันตราย", "สั่งให้ใส่ชุดความปลอดภัยส่วนบุคคล"],
    ["Under repair", "Status indicating equipment is currently being fixed.", "The port crane is under repair.", "กำลังซ่อมแซม", "สถานะอุปกรณ์ที่กำลังซ่อม"],
    ["Test the system", "Command to verify if equipment works correctly.", "Test the system before departure.", "ทดสอบระบบ", "คำสั่งให้ลองใช้งานระบบ"],
    ["Welcome on board", "A greeting for someone arriving on the ship.", "Welcome on board, Mr. Inspector.", "ยินดีต้อนรับขึ้นเรือ", "คำทักทายเมื่อมีคนขึ้นมาบนเรือ"],
    ["What is your ETA?", "Asking for the Estimated Time of Arrival.", "Vessel ahead, what is your ETA?", "คุณจะมาถึงเมื่อไหร่", "ถามเวลาโดยประมาณที่จะมาถึง"],
    ["My ETA is 1400 hours.", "Stating the Estimated Time of Arrival is 2 PM.", "My ETA is 1400 hours local time.", "ฉันจะไปถึงเวลา 1400", "แจ้งเวลาที่จะไปถึงคือ 14:00 น."],
    ["Stand clear", "A warning to move away from a potentially dangerous area.", "Stand clear of the mooring ropes!", "ถอยออกไป", "คำเตือนให้ออกห่างจากพื้นที่อันตราย"],
    ["All clear", "Confirmation that an area is safe or an operation is complete.", "All clear aft, you can let go.", "ทุกอย่างเรียบร้อย", "ยืนยันว่าปลอดภัยหรือเสร็จสิ้น"],
    ["Single up", "To reduce the number of mooring lines to one forward and one aft before departure.", "Single up forward and aft.", "ปลดเชือกเหลือเส้นเดียว", "การลดเชือกผูกเรือเหลือหัวท้ายอย่างละเส้น"],
    ["I am altering my course to starboard.", "Informing other vessels of a turn to the right.", "VTS, I am altering my course to starboard.", "ฉันกำลังเปลี่ยนเข็มไปทางกราบขวา", "แจ้งว่ากำลังเลี้ยวขวา"],
    ["I am altering my course to port.", "Informing other vessels of a turn to the left.", "Vessel astern, I am altering my course to port.", "ฉันกำลังเปลี่ยนเข็มไปทางกราบซ้าย", "แจ้งว่ากำลังเลี้ยวซ้าย"],
    ["Engine on standby", "Informing that the main engine is ready for immediate use.", "Bridge, engine on standby.", "เครื่องยนต์พร้อมใช้งาน", "แจ้งว่าเครื่องจักรใหญ่พร้อมใช้งานทันที"],
    ["Time to wake up", "Call to wake a crew member.", "Time to wake up for your watch.", "ได้เวลาตื่นแล้ว", "ปลุกลูกเรือ"],
    ["Breakfast is ready", "Announcement that morning meal is served.", "Breakfast is ready in the mess room.", "อาหารเช้าพร้อมแล้ว", "แจ้งว่าอาหารเช้าพร้อม"],
    ["Lunch is served", "Announcement for midday meal.", "Lunch is served.", "อาหารเที่ยงพร้อมแล้ว", "แจ้งว่าอาหารเที่ยงพร้อม"],
    ["Dinner is ready", "Announcement for evening meal.", "Dinner is ready in the galley.", "อาหารเย็นพร้อมแล้ว", "แจ้งว่าอาหารเย็นพร้อม"],
    ["Coffee break", "Time for a short rest and refreshment.", "Let's take a 15-minute coffee break.", "พักดื่มกาแฟ", "เวลาพักสั้นๆ"],
    ["Enjoy your meal", "Polite wish before eating.", "Enjoy your meal, Captain.", "ทานอาหารให้อร่อย", "คำอวยพรก่อนกินอาหาร"],
    ["Pass the salt", "Requesting seasoning at the table.", "Please pass the salt.", "ส่งเกลือให้หน่อย", "ขอให้ส่งเครื่องปรุง"],
    ["Clean the table", "Instruction to wipe the dining surface.", "Clean the table after eating.", "เช็ดโต๊ะ", "ทำความสะอาดโต๊ะอาหาร"],
    ["Wash the dishes", "Instruction to clean the plates.", "It's your turn to wash the dishes.", "ล้างจาน", "ทำความสะอาดจานชาม"],
    ["Empty the trash", "Instruction to dispose of garbage.", "Empty the trash bin in the galley.", "ทิ้งขยะ", "นำขยะไปทิ้ง"],
    ["I am tired", "Stating fatigue.", "I am tired after a long watch.", "ฉันเหนื่อย", "บอกอาการเหนื่อยล้า"],
    ["I need some rest", "Stating the need for sleep.", "I need some rest before my next shift.", "ฉันต้องการพักผ่อน", "บอกว่าต้องการนอนพัก"],
    ["Going to sleep", "Announcing intention to bed.", "I am going to sleep now.", "กำลังจะไปนอน", "บอกว่าจะไปนอน"],
    ["Set the alarm", "Instruction to prepare a wake-up call.", "Set the alarm for 0400.", "ตั้งนาฬิกาปลุก", "ตั้งเวลาปลุก"],
    ["Turn off the lights", "Command to extinguish room illumination.", "Turn off the lights when leaving.", "ปิดไฟ", "ปิดสวิตช์ไฟ"],
    ["Close the door", "Command to shut the entrance.", "Close the door to keep the noise out.", "ปิดประตู", "ปิดประตูห้อง"],
    ["Open the window", "Command to allow fresh air.", "Open the window for ventilation.", "เปิดหน้าต่าง", "เปิดหน้าต่างระบายอากาศ"],
    ["Sweep the deck", "Instruction to brush the floor.", "Sweep the deck outside the accommodation.", "กวาดดาดฟ้า", "ทำความสะอาดพื้นดาดฟ้า"],
    ["Mop the floor", "Instruction to wash the ground.", "Mop the floor in the corridor.", "ถูพื้น", "ถูทำความสะอาดทางเดิน"],
    ["Wipe the glass", "Instruction to clean windows/mirrors.", "Wipe the glass on the bridge.", "เช็ดกระจก", "ทำความสะอาดกระจก"],
    ["Where is the Chief Officer?", "Asking for a person's location.", "Where is the Chief Officer right now?", "ต้นเรืออยู่ไหน", "ถามหาตำแหน่งบุคคล"],
    ["Have you seen the Captain?", "Inquiring about the Master.", "Have you seen the Captain this morning?", "คุณเห็นกัปตันไหม", "ถามหากัปตัน"],
    ["I am going to the bridge", "Stating destination.", "I am going to the bridge to report.", "ฉันกำลังไปที่สะพานเดินเรือ", "บอกว่าจะไปสะพานเดินเรือ"],
    ["Please call the engine room", "Requesting a phone call.", "Please call the engine room for pressure check.", "กรุณาโทรหาห้องเครื่อง", "ขอให้ติดต่อห้องเครื่อง"],
    ["Is the coffee ready?", "Asking if the beverage is prepared.", "Is the coffee ready yet?", "กาแฟพร้อมหรือยัง", "ถามว่ากาแฟเสร็จหรือยัง"],
    ["Can you help me lift this?", "Asking for physical assistance.", "Can you help me lift this box?", "คุณช่วยฉันยกสิ่งนี้ได้ไหม", "ขอความช่วยเหลือในการยกของ"],
    ["Where is the tool box?", "Asking for equipment location.", "Where is the tool box kept?", "กล่องเครื่องมืออยู่ไหน", "ถามหาที่เก็บเครื่องมือ"],
    ["Pass me the spanner", "Requesting a specific tool.", "Pass me the spanner, please.", "ส่งประแจให้ฉันหน่อย", "ขอให้ส่งเครื่องมือช่าง"],
    ["Hold this line tight", "Instruction to maintain tension.", "Hold this line tight while I tie it.", "จับเชือกนี้ให้ตึง", "สั่งให้ดึงเชือกไว้"],
    ["Be careful, it is heavy", "Warning about weight.", "Be careful, it is heavy equipment.", "ระวัง มันหนักมาก", "เตือนเรื่องน้ำหนัก"],
    ["It is very hot today", "Commenting on temperature.", "It is very hot today in the engine room.", "วันนี้อากาศร้อนมาก", "พูดถึงสภาพอากาศที่ร้อน"],
    ["The sea is getting rough", "Commenting on wave conditions.", "Secure everything, the sea is getting rough.", "คลื่นลมเริ่มแรงขึ้น", "พูดถึงสภาพคลื่นลมทะเล"],
    ["Did you sleep well?", "Polite morning inquiry.", "Good morning, did you sleep well?", "คุณหลับสบายไหม", "ถามไถ่การนอนหลับ"],
    ["My shift is over", "Stating end of duty.", "My shift is over, I am going below.", "กะของฉันจบลงแล้ว", "บอกว่าหมดเวลาทำงาน"],
    ["Who is on watch now?", "Asking about current duty personnel.", "Who is on watch now at the bridge?", "ตอนนี้ใครเข้าเวรอยู่", "ถามหาคนเข้ากะ"],
    ["Please sign the logbook", "Requesting a signature for records.", "Please sign the logbook before leaving.", "กรุณาเซ็นชื่อในปูมเรือ", "ขอให้เซ็นบันทึก"],
    ["Where are the clean rags?", "Asking for cleaning materials.", "Where are the clean rags for wiping oil?", "ผ้าขี้ริ้วสะอาดอยู่ไหน", "ถามหาผ้าเช็ดทำความสะอาด"],
    ["We need more garbage bags", "Stating a supply shortage.", "We need more garbage bags in the galley.", "เราต้องการถุงขยะเพิ่ม", "บอกว่าถุงขยะหมด"],
    ["Check the water level", "Instruction to verify liquid amount.", "Check the water level in the boiler.", "ตรวจสอบระดับน้ำ", "สั่งให้ดูระดับน้ำ"],
    ["Start the ventilation", "Instruction to turn on air flow.", "Start the ventilation in the hold.", "เปิดระบบระบายอากาศ", "สั่งให้เปิดพัดลมดูดอากาศ"],
    ["The power is out", "Reporting electrical failure.", "The power is out in the accommodation.", "ไฟดับ", "แจ้งเหตุไฟฟ้าดับ"],
    ["Reboot the computer", "Instruction to restart a system.", "Reboot the computer on the ECDIS.", "รีสตาร์ทคอมพิวเตอร์", "สั่งให้เปิดเครื่องใหม่"],
    ["Printer is out of paper", "Reporting office supply issue.", "The bridge printer is out of paper.", "เครื่องพิมพ์กระดาษหมด", "แจ้งปัญหากระดาษหมด"],
    ["I will fix it", "Promising to repair something.", "Leave it there, I will fix it.", "ฉันจะซ่อมมันเอง", "อาสาที่จะซ่อมแซม"],
    ["It is broken", "Stating something is non-functional.", "The port wiper is broken.", "มันพังแล้ว", "บอกว่าอุปกรณ์เสีย"],
    ["We need spare parts", "Stating a requirement for replacements.", "We need spare parts for the pump.", "เราต้องการอะไหล่", "แจ้งว่าต้องใช้อะไหล่ซ่อม"],
    ["Check the inventory", "Instruction to count stock.", "Check the inventory of safety gear.", "ตรวจสอบสินค้าคงคลัง", "สั่งให้นับสต็อก"],
    ["Send an email", "Instruction to transmit an electronic message.", "Send an email to the port agent.", "ส่งอีเมล", "สั่งให้ส่งจดหมายอิเล็กทรอนิกส์"],
    ["Read the manual", "Instruction to consult documentation.", "Read the manual before operating.", "อ่านคู่มือ", "สั่งให้อ่านวิธีใช้"],
    ["Follow the procedure", "Instruction to adhere to rules.", "Follow the procedure for enclosed space entry.", "ทำตามขั้นตอน", "สั่งให้ปฏิบัติตามกฎ"],
    ["Are you ready?", "Asking if prepared.", "Are you ready for departure?", "คุณพร้อมหรือยัง", "ถามความพร้อม"],
    ["Wait a minute", "Requesting a brief pause.", "Wait a minute, I am getting my coat.", "รอสักครู่", "ขอให้รอแป๊บหนึ่ง"],
    ["Hurry up", "Urging speed.", "Hurry up, the pilot is waiting.", "รีบหน่อย", "เร่งให้เร็วขึ้น"],
    ["Take your time", "Advising not to rush.", "Take your time, no need to rush.", "ตามสบาย ไม่ต้องรีบ", "บอกว่าไม่ต้องรีบร้อน"],
    ["Good job", "Praising work.", "Good job on the deck painting.", "ทำได้ดีมาก", "ชมเชยการทำงาน"],
    ["Thank you for your help", "Expressing gratitude.", "Thank you for your help with the cargo.", "ขอบคุณสำหรับความช่วยเหลือ", "กล่าวขอบคุณ"],
    ["No problem", "Responding to thanks.", "No problem, glad to help.", "ไม่มีปัญหา", "ตอบรับคำขอบคุณ"],
    ["Excuse me", "Polite interruption.", "Excuse me, Captain, you have a call.", "ขอโทษนะครับ", "คำพูดก่อนขัดจังหวะ"],
    ["I am sorry", "Apologizing.", "I am sorry for the delay.", "ฉันขอโทษ", "กล่าวขอโทษ"],
    ["It was my mistake", "Taking responsibility for an error.", "It was my mistake in the logbook.", "มันเป็นความผิดของฉันเอง", "ยอมรับความผิด"],
    ["Be careful", "Warning to exercise caution.", "Be careful when walking on the wet deck.", "ระมัดระวังด้วย", "เตือนให้ระวัง"],
    ["Look out", "Sudden warning of danger.", "Look out! The load is swinging.", "ระวัง!", "เตือนภัยกะทันหัน"],
    ["Do not touch", "Commanding to leave something alone.", "Do not touch the wet paint.", "ห้ามแตะต้อง", "สั่งห้ามจับ"],
    ["Keep this area clean", "Instruction regarding hygiene.", "Keep this area clean at all times.", "รักษาความสะอาดบริเวณนี้", "สั่งให้รักษาความสะอาด"],
    ["Wash your hands", "Instruction for personal hygiene.", "Wash your hands before entering the galley.", "ล้างมือของคุณ", "สั่งให้ล้างมือก่อน"],
    ["Wear a helmet", "Instruction for safety gear.", "Wear a helmet in the engine room.", "สวมหมวกนิรภัย", "สั่งให้ใส่หมวกแข็ง"],
    ["Wear safety shoes", "Instruction for protective footwear.", "Wear safety shoes on deck.", "สวมรองเท้านิรภัย", "สั่งให้ใส่รองเท้าเซฟตี้"],
    ["Use ear protection", "Instruction to prevent hearing damage.", "Use ear protection near the generators.", "ใช้อุปกรณ์ป้องกันเสียง", "สั่งให้ใส่ที่อุดหู"],
    ["Put on gloves", "Instruction to protect hands.", "Put on gloves before handling the chemicals.", "สวมถุงมือ", "สั่งให้ใส่ถุงมือ"],
    ["Secure the ladder", "Instruction to make a climbing path safe.", "Secure the ladder before climbing.", "ยึดบันไดให้แน่น", "สั่งให้มัดบันได"],
    ["Are you feeling okay?", "Inquiring about health.", "You look pale, are you feeling okay?", "คุณรู้สึกโอเคไหม", "ถามอาการป่วย"],
    ["I feel sick", "Stating illness.", "I feel sick, I need to see the medic.", "ฉันรู้สึกไม่สบาย", "บอกว่าป่วย"],
    ["I have a headache", "Stating a specific pain.", "I have a headache from the noise.", "ฉันปวดหัว", "บอกว่าปวดศีรษะ"],
    ["Get the first aid kit", "Instruction to fetch medical supplies.", "Get the first aid kit from the bridge.", "ไปหยิบชุดปฐมพยาบาลมา", "สั่งให้เอาตู้ยามา"],
    ["Call the doctor", "Instruction to summon medical help.", "Call the doctor via satellite phone.", "โทรเรียกหมอ", "สั่งให้ติดต่อแพทย์"],
    ["Drink more water", "Advice for hydration.", "Drink more water, it's hot outside.", "ดื่มน้ำให้มากขึ้น", "แนะนำให้ดื่มน้ำ"],
    ["Take some medicine", "Advice for illness.", "Take some medicine and lie down.", "กินยาซะ", "บอกให้กินยา"],
    ["Check the fire extinguisher", "Instruction to verify safety equipment.", "Check the fire extinguisher pressure.", "ตรวจสอบถังดับเพลิง", "สั่งให้เช็คถังดับเพลิง"],
    ["Where is the nearest exit?", "Asking for escape route.", "Where is the nearest exit from here?", "ทางออกที่ใกล้ที่สุดอยู่ไหน", "ถามหาทางออกฉุกเฉิน"],
    ["Follow the signs", "Instruction to use visual guidance.", "Follow the signs to the muster station.", "เดินตามป้ายบอกทาง", "สั่งให้ตามป้ายไป"],
    ["Stay calm", "Advice during an emergency.", "Stay calm and put on your lifejacket.", "ตั้งสติไว้", "บอกให้ใจเย็นๆ"],
    ["Do not panic", "Instruction to avoid hysteria.", "Do not panic, the fire is under control.", "อย่าตื่นตระหนก", "ห้ามตกใจกลัว"],
    ["Listen to the alarm", "Instruction to pay attention to signals.", "Listen to the alarm and act accordingly.", "ฟังเสียงสัญญาณเตือนภัย", "สั่งให้ฟังสัญญาณ"],
    ["Lock the door", "Command to secure an entrance.", "Lock the door to the bonded store.", "ล็อคประตู", "สั่งให้ล็อคห้อง"],
    ["Where is the key?", "Asking for access tool.", "Where is the key to the paint locker?", "กุญแจอยู่ไหน", "ถามหากุญแจ"],
    ["Give me the key", "Requesting the access tool.", "Give me the key to the bridge.", "เอากุญแจมาให้ฉัน", "ขอรับกุญแจ"],
    ["Open the hatch", "Command to remove cover.", "Open the hatch for cargo loading.", "เปิดฝาระวาง", "สั่งให้เปิดฝาระวาง"],
    ["Close the hatch", "Command to replace cover.", "Close the hatch, it is starting to rain.", "ปิดฝาระวาง", "สั่งให้ปิดฝาระวาง"],
    ["Check the temperature of the cargo", "Instruction for cargo care.", "Check the temperature of the reefer container.", "ตรวจสอบอุณหภูมิของสินค้า", "สั่งให้ดูอุณหภูมิตู้"],
    ["Monitor the pressure", "Instruction for ongoing observation.", "Monitor the pressure in the pipes.", "เฝ้าระวังแรงดัน", "สั่งให้คอยดูความดัน"],
    ["Report any leakage", "Instruction to notify of spills.", "Report any leakage immediately.", "รายงานหากมีการรั่วไหล", "สั่งให้แจ้งถ้ารั่ว"],
    ["Wipe up the oil", "Instruction to clean a spill.", "Wipe up the oil on the deck.", "เช็ดคราบน้ำมัน", "สั่งให้เช็ดน้ำมัน"],
    ["Use the dispersant", "Instruction to apply chemical cleaner.", "Use the dispersant on the spill.", "ใช้น้ำยาขจัดคราบ", "สั่งให้ใช้น้ำยาล้าง"],
    ["Empty the bilge", "Instruction to pump out bottom water.", "Empty the bilge tank before arrival.", "สูบน้ำท้องเรือออก", "สั่งให้ปั๊มน้ำทิ้ง"],
    ["Check the sounding pipe", "Instruction to measure liquid level.", "Check the sounding pipe for water.", "ตรวจสอบท่อหยั่งน้ำ", "สั่งให้วัดระดับน้ำจากท่อ"],
    ["Sound the alarm", "Command to trigger warning system.", "Sound the alarm if you see fire.", "กดสัญญาณเตือนภัย", "สั่งให้กดกริ่งเตือนภัย"],
    ["Is the equipment secure?", "Asking if gear is tied down safely.", "Is the equipment secure for rough seas?", "อุปกรณ์ถูกยึดแน่นหรือยัง", "ถามว่าผูกของแน่นไหม"],
    ["Tighten the lashings", "Command to increase tension on restraints.", "Tighten the lashings on the containers.", "รัดสายรัดให้แน่นขึ้น", "สั่งให้รัดสินค้าเพิ่ม"],
    ["Loosen the turnbuckle", "Command to decrease tension.", "Loosen the turnbuckle to release the wire.", "คลายเกลียวเร่ง", "สั่งให้คลายเกลียวเร่ง"],
    ["Everything is in order", "Statement that all is well.", "Everything is in order, Captain.", "ทุกอย่างเรียบร้อยดี", "รายงานว่าปกติทุกอย่าง"]
  ];

  manualPhrases.forEach(p => {
    generatedVocab.push({ term: p[0], definition: p[1], example: p[2], category: "Communication", thai_translation: p[3], thai_meaning: p[4], level: "Cadet Level" });
  });

  // 2. Standard Communication Phrases (SMCP) (100 items)
  const standardPhrases = [
    ["What is your present maximum draft?", "SMCP asking for deepest submerged point.", "What is your present maximum draft?", "อัตรากินน้ำลึกสูงสุดปัจจุบันของคุณคือเท่าไร", "ถามระดับกินน้ำลึกสูงสุด"],
    ["My present maximum draft is", "SMCP stating deepest submerged point.", "My present maximum draft is 10 meters.", "อัตรากินน้ำลึกสูงสุดปัจจุบันของฉันคือ", "บอกระดับกินน้ำลึกสูงสุด"],
    ["Are you underway?", "SMCP asking if vessel is moving/free.", "Are you underway?", "คุณกำลังเดินเรืออยู่หรือไม่", "ถามว่าเรือกำลังเคลื่อนที่ไหม"],
    ["I am underway", "SMCP stating vessel is moving/free.", "I am underway and making way.", "ฉันกำลังเดินเรือ", "บอกว่าเรือไม่ได้จอดสมอ"],
    ["Are you at anchor?", "SMCP asking if vessel is anchored.", "Are you at anchor?", "คุณจอดทอดสมออยู่หรือไม่", "ถามว่าทอดสมอไหม"],
    ["I am at anchor", "SMCP stating vessel is anchored.", "I am at anchor at position Alpha.", "ฉันจอดทอดสมออยู่", "บอกว่าทอดสมอแล้ว"],
    ["I require a pilot", "SMCP requesting pilotage assistance.", "I require a pilot at the pilot station.", "ฉันต้องการผู้นำร่อง", "ขอรับบริการผู้นำร่อง"],
    ["Do you require a pilot?", "SMCP asking if pilotage is needed.", "Do you require a pilot?", "คุณต้องการผู้นำร่องหรือไม่", "ถามว่าต้องการผู้นำร่องไหม"],
    ["Pilot boat is approaching", "SMCP informing that pilot is coming.", "Pilot boat is approaching from starboard.", "เรือผู้นำร่องกำลังเข้ามาใกล้", "แจ้งว่าเรือนำร่องกำลังมา"],
    ["You must anchor in a different position", "SMCP instruction to change anchorage.", "You must anchor in a different position.", "คุณต้องเปลี่ยนจุดทอดสมอ", "สั่งให้ย้ายที่จอดสมอ"],
    ["Do not overtake", "SMCP warning not to pass another vessel.", "Do not overtake in the narrow channel.", "ห้ามแซง", "ห้ามขับเรือแซง"],
    ["Vessel is not under command", "SMCP stating ship cannot maneuver.", "Warning, vessel is not under command.", "เรือไม่สามารถบังคับได้", "แจ้งว่าเรือเสียการควบคุม"],
    ["I have a leak below water line", "SMCP reporting underwater damage.", "I have a leak below water line.", "เรือของฉันมีรอยรั่วใต้ระดับน้ำ", "แจ้งเหตุเรือรั่วใต้น้ำ"],
    ["Visibility is decreasing", "SMCP reporting worsening sight.", "Visibility is decreasing due to fog.", "ทัศนวิสัยกำลังลดลง", "แจ้งว่าการมองเห็นแย่ลง"],
    ["Visibility is increasing", "SMCP reporting improving sight.", "Visibility is increasing now.", "ทัศนวิสัยกำลังเพิ่มขึ้น", "แจ้งว่าการมองเห็นดีขึ้น"],
    ["What is the wind direction and force?", "SMCP asking for wind data.", "What is the wind direction and force?", "ทิศทางและความเร็วลมคืออะไร", "ถามทิศและกำลังลม"],
    ["Wind direction is", "SMCP stating wind data.", "Wind direction is North, force 5.", "ทิศทางลมคือ", "บอกทิศทางลม"],
    ["Is the turning effect of the propeller very strong?", "SMCP asking about maneuverability.", "Is the turning effect of the propeller very strong?", "แรงผลักด้านข้างของใบพัดแรงมากหรือไม่", "ถามเรื่องแรงบิดใบพัด"],
    ["The turning effect of the propeller is very strong", "SMCP stating strong maneuverability effect.", "The turning effect of the propeller is very strong.", "แรงผลักด้านข้างของใบพัดแรงมาก", "บอกว่าแรงบิดใบพัดสูง"],
    ["Stand by starboard anchor", "SMCP command to prepare right anchor.", "Stand by starboard anchor.", "เตรียมพร้อมสมอกราบขวา", "สั่งเตรียมทิ้งสมอขวา"],
    ["Let go starboard anchor", "SMCP command to drop right anchor.", "Let go starboard anchor.", "ทิ้งสมอกราบขวา", "สั่งทิ้งสมอขวา"],
    ["How many shackles are left?", "SMCP asking for anchor chain length remaining.", "How many shackles are left?", "เหลือโซ่สมอกี่ข้อ", "ถามความยาวโซ่สมอที่เหลือ"],
    ["Anchor is clear of the water", "SMCP stating anchor is hoisted.", "Anchor is clear of the water.", "สมอพ้นน้ำแล้ว", "แจ้งว่าดึงสมอขึ้นพ้นน้ำแล้ว"],
    ["Anchor is foul", "SMCP stating anchor is tangled.", "Anchor is foul with a cable.", "สมอติดขัด", "แจ้งว่าสมอพันกับสิ่งอื่น"],
    ["Send heaving line", "SMCP command to throw a light rope.", "Send heaving line to the tug.", "ส่งเชือกนำ", "สั่งให้โยนเชือกเล็ก"],
    ["Make fast fore and aft", "SMCP command to secure ship completely.", "Make fast fore and aft.", "ผูกเชือกหัวและท้ายเรือให้แน่น", "สั่งผูกเชือกหัวท้าย"],
    ["Are the bow thrusters operational?", "SMCP asking if forward propellers work.", "Are the bow thrusters operational?", "ใบพัดหัวเรือใช้งานได้หรือไม่", "ถามสถานะใบพัดหัวเรือ"],
    ["The bow thrusters are operational", "SMCP stating forward propellers work.", "The bow thrusters are operational.", "ใบพัดหัวเรือใช้งานได้", "บอกว่าใบพัดหัวเรือใช้ได้"],
    ["What is your ETA?", "SMCP asking for estimated time of arrival.", "What is your ETA at the buoy?", "เวลาถึงโดยประมาณของคุณคือเท่าไร", "ถามเวลาถึง"],
    ["What is your ETD?", "SMCP asking for estimated time of departure.", "What is your ETD from the berth?", "เวลาออกเดินทางโดยประมาณของคุณคือเท่าไร", "ถามเวลาออกเรือ"],
    ["I have a fire in the engine room", "SMCP reporting specific fire location.", "I have a fire in the engine room.", "มีไฟไหม้ในห้องเครื่อง", "แจ้งไฟไหม้ห้องเครื่อง"],
    ["Are you on fire?", "SMCP asking if vessel is burning.", "Are you on fire?", "เรือของคุณไฟไหม้หรือไม่", "ถามว่ามีไฟไหม้ไหม"],
    ["I am not on fire", "SMCP stating no fire.", "I am not on fire.", "เรือฉันไม่ได้ไฟไหม้", "ปฏิเสธว่าไม่มีไฟไหม้"],
    ["Do you require medical assistance?", "SMCP asking if medical help is needed.", "Do you require medical assistance?", "คุณต้องการความช่วยเหลือทางการแพทย์หรือไม่", "ถามว่าต้องการหมอไหม"],
    ["I require medical assistance", "SMCP stating medical help is needed.", "I require medical assistance.", "ฉันต้องการความช่วยเหลือทางการแพทย์", "ขอความช่วยเหลือทางการแพทย์"],
    ["What is your course?", "SMCP asking for direction of travel.", "What is your course?", "เข็มเดินเรือของคุณคืออะไร", "ถามทิศทางเรือ"],
    ["My course is", "SMCP stating direction of travel.", "My course is 180 degrees.", "เข็มเดินเรือของฉันคือ", "บอกทิศทางเรือ"],
    ["What is your speed?", "SMCP asking for velocity.", "What is your speed?", "ความเร็วของคุณคืออะไร", "ถามความเร็วเรือ"],
    ["My speed is", "SMCP stating velocity.", "My speed is 12 knots.", "ความเร็วของฉันคือ", "บอกความเร็วเรือ"],
    ["Alter course to starboard", "SMCP command/advice to turn right.", "Alter course to starboard.", "เปลี่ยนเข็มไปทางกราบขวา", "สั่งให้เลี้ยวขวา"],
    ["Alter course to port", "SMCP command/advice to turn left.", "Alter course to port.", "เปลี่ยนเข็มไปทางกราบซ้าย", "สั่งให้เลี้ยวซ้าย"],
    ["Stop your vessel", "SMCP command to halt completely.", "Stop your vessel immediately.", "หยุดเรือของคุณ", "สั่งให้หยุดเรือ"],
    ["You are proceeding into danger", "SMCP warning of imminent hazard.", "You are proceeding into danger.", "คุณกำลังมุ่งหน้าสู่อันตราย", "เตือนว่ากำลังเข้าสู่อันตราย"],
    ["Navigation is closed", "SMCP stating waterway is shut.", "Navigation is closed in the channel.", "ปิดการเดินเรือ", "แจ้งว่าปิดเส้นทางน้ำ"],
    ["I am sinking", "SMCP reporting vessel is going down.", "I am sinking.", "เรือฉันกำลังจะจม", "แจ้งว่าเรือกำลังจม"],
    ["Can you proceed without assistance?", "SMCP asking if vessel can move alone.", "Can you proceed without assistance?", "คุณสามารถเดินทางต่อโดยไม่ต้องช่วยได้ไหม", "ถามว่าไปต่อเองได้ไหม"],
    ["I can proceed without assistance", "SMCP stating no tow is needed.", "I can proceed without assistance.", "ฉันสามารถเดินทางต่อโดยไม่ต้องช่วยได้", "บอกว่าไปต่อเองได้"],
    ["What is your cargo?", "SMCP asking what is being transported.", "What is your cargo?", "สินค้าของคุณคืออะไร", "ถามชนิดสินค้า"],
    ["My cargo is", "SMCP stating what is being transported.", "My cargo is crude oil.", "สินค้าของฉันคือ", "บอกชนิดสินค้า"],
    ["Do you carry dangerous goods?", "SMCP asking about hazardous cargo.", "Do you carry dangerous goods?", "คุณบรรทุกสินค้าอันตรายหรือไม่", "ถามว่ามีสินค้าอันตรายไหม"],
    ["I carry dangerous goods", "SMCP stating hazardous cargo is aboard.", "I carry dangerous goods class 3.", "ฉันบรรทุกสินค้าอันตราย", "บอกว่ามีสินค้าอันตราย"],
    ["Are you adrift?", "SMCP asking if vessel is floating unguided.", "Are you adrift?", "คุณกำลังลอยลอยลำอยู่หรือไม่", "ถามว่าเรือลอยไปตามน้ำไหม"],
    ["I am adrift", "SMCP stating vessel is floating unguided.", "I am adrift.", "ฉันกำลังลอยลอยลำอยู่", "บอกว่าเรือลอยไปตามน้ำ"],
    ["What is the sea state?", "SMCP asking about wave conditions.", "What is the sea state?", "สภาพทะเลเป็นอย่างไร", "ถามสภาพคลื่นทะเล"],
    ["The sea state is", "SMCP stating wave conditions.", "The sea state is rough.", "สภาพทะเลคือ", "บอกสภาพคลื่นทะเล"],
    ["Is the visibility expected to change?", "SMCP asking about weather forecast.", "Is the visibility expected to change?", "คาดว่าทัศนวิสัยจะเปลี่ยนแปลงหรือไม่", "ถามการพยากรณ์ทัศนวิสัย"],
    ["Are there any navigational warnings?", "SMCP asking about hazards.", "Are there any navigational warnings?", "มีคำเตือนการเดินเรือหรือไม่", "ถามหาคำเตือนเดินเรือ"],
    ["Ice warning", "SMCP alerting about ice hazard.", "Ice warning in your area.", "คำเตือนเรื่องน้ำแข็ง", "เตือนภัยภูเขาน้ำแข็ง"],
    ["Tide is rising", "SMCP stating water level is going up.", "Tide is rising.", "น้ำกำลังขึ้น", "แจ้งว่าน้ำกำลังขึ้น"],
    ["Tide is falling", "SMCP stating water level is going down.", "Tide is falling.", "น้ำกำลังลง", "แจ้งว่าน้ำกำลังลง"],
    ["Current is", "SMCP stating water flow speed/direction.", "Current is 2 knots.", "กระแสน้ำคือ", "บอกกระแสน้ำ"],
    ["What is your freeboard?", "SMCP asking for height above water.", "What is your freeboard?", "ระยะกราบพ้นน้ำของคุณคืออะไร", "ถามระยะพ้นน้ำ"],
    ["My freeboard is", "SMCP stating height above water.", "My freeboard is 5 meters.", "ระยะกราบพ้นน้ำของฉันคือ", "บอกระยะพ้นน้ำ"],
    ["Rig the pilot ladder", "SMCP command to deploy boarding ladder.", "Rig the pilot ladder on the port side.", "เตรียมบันไดนำร่อง", "สั่งให้กางบันไดนำร่อง"],
    ["Pilot ladder is rigged", "SMCP stating boarding ladder is ready.", "Pilot ladder is rigged.", "บันไดนำร่องพร้อมแล้ว", "แจ้งว่าบันไดกางเสร็จแล้ว"],
    ["Stand by the engine", "SMCP command to prepare main propulsion.", "Stand by the engine.", "เตรียมพร้อมเครื่องยนต์", "สั่งเตรียมพร้อมเครื่องจักร"],
    ["Engine is on standby", "SMCP stating main propulsion is ready.", "Engine is on standby.", "เครื่องยนต์พร้อมแล้ว", "แจ้งว่าเครื่องจักรพร้อมใช้งาน"],
    ["Full ahead", "SMCP command for maximum forward speed.", "Full ahead.", "เดินหน้าเต็มตัว", "สั่งเดินหน้าเต็มที่"],
    ["Half ahead", "SMCP command for medium forward speed.", "Half ahead.", "เดินหน้าครึ่งตัว", "สั่งเดินหน้าครึ่งความเร็ว"],
    ["Slow ahead", "SMCP command for low forward speed.", "Slow ahead.", "เดินหน้าช้า", "สั่งเดินหน้าช้าๆ"],
    ["Stop engine", "SMCP command to halt propulsion.", "Stop engine.", "หยุดเครื่องยนต์", "สั่งหยุดเครื่องจักร"],
    ["Slow astern", "SMCP command for low reverse speed.", "Slow astern.", "ถอยหลังช้า", "สั่งถอยหลังช้าๆ"],
    ["Half astern", "SMCP command for medium reverse speed.", "Half astern.", "ถอยหลังครึ่งตัว", "สั่งถอยหลังครึ่งความเร็ว"],
    ["Full astern", "SMCP command for maximum reverse speed.", "Full astern.", "ถอยหลังเต็มตัว", "สั่งถอยหลังเต็มที่"],
    ["Midships", "SMCP command to center the rudder.", "Midships.", "หางเสือตรง", "สั่งให้ตั้งหางเสือตรง"],
    ["Port five", "SMCP command to turn rudder 5 degrees left.", "Port five.", "ซ้ายห้าองศา", "สั่งหันหางเสือซ้ายห้าองศา"],
    ["Starboard ten", "SMCP command to turn rudder 10 degrees right.", "Starboard ten.", "ขวาสิบองศา", "สั่งหันหางเสือขวาสิบองศา"],
    ["Hard-a-port", "SMCP command to turn rudder fully left.", "Hard-a-port.", "ซ้ายสุด", "สั่งหันหางเสือซ้ายสุด"],
    ["Hard-a-starboard", "SMCP command to turn rudder fully right.", "Hard-a-starboard.", "ขวาสุด", "สั่งหันหางเสือขวาสุด"],
    ["Steady as she goes", "SMCP command to keep current heading.", "Steady as she goes.", "ถือเข็มนี้ไว้", "สั่งให้ประคองเรือตามทิศทางนี้"],
    ["Let go the tug", "SMCP command to release towing vessel.", "Let go the tug.", "ปล่อยเรือลากจูง", "สั่งปลดเชือกเรือทัก"],
    ["Make fast the tug", "SMCP command to secure towing vessel.", "Make fast the tug forward.", "ผูกเรือลากจูงให้แน่น", "สั่งผูกเรือทัก"],
    ["Use bow thruster", "SMCP command to apply forward side propulsion.", "Use bow thruster to port.", "ใช้ใบพัดหัวเรือ", "สั่งใช้ทรัสเตอร์หัวเรือ"],
    ["Use stern thruster", "SMCP command to apply rear side propulsion.", "Use stern thruster to starboard.", "ใช้ใบพัดท้ายเรือ", "สั่งใช้ทรัสเตอร์ท้ายเรือ"],
    ["Are the hatches closed?", "SMCP asking if cargo holds are sealed.", "Are the hatches closed?", "ฝาระวางปิดหรือยัง", "ถามว่าปิดฝาระวางหรือยัง"],
    ["The hatches are closed", "SMCP stating cargo holds are sealed.", "The hatches are closed.", "ฝาระวางปิดแล้ว", "แจ้งว่าปิดฝาระวางแล้ว"],
    ["Is the cargo secure?", "SMCP asking if freight is tied down.", "Is the cargo secure?", "สินค้าถูกยึดแน่นหรือยัง", "ถามว่ามัดสินค้าแน่นไหม"],
    ["The cargo is secure", "SMCP stating freight is tied down.", "The cargo is secure.", "สินค้าถูกยึดแน่นแล้ว", "แจ้งว่ามัดสินค้าแน่นแล้ว"],
    ["Start discharging", "SMCP command to begin unloading.", "Start discharging the oil.", "เริ่มขนถ่ายสินค้าลง", "สั่งให้เริ่มเอาของลง"],
    ["Stop discharging", "SMCP command to halt unloading.", "Stop discharging immediately.", "หยุดขนถ่ายสินค้าลง", "สั่งให้หยุดเอาของลง"],
    ["Start loading", "SMCP command to begin taking on freight.", "Start loading the containers.", "เริ่มบรรทุกสินค้า", "สั่งให้เริ่มเอาของขึ้นเรือ"],
    ["Stop loading", "SMCP command to halt taking on freight.", "Stop loading.", "หยุดบรรทุกสินค้า", "สั่งให้หยุดเอาของขึ้นเรือ"],
    ["We have a stowaway", "SMCP reporting an unauthorized person.", "We have a stowaway on board.", "มีผู้ลักลอบขึ้นเรือ", "แจ้งว่ามีคนแอบขึ้นเรือ"],
    ["We have a piracy attack", "SMCP reporting armed robbery attempt.", "We have a piracy attack.", "มีโจรสลัดโจมตี", "แจ้งเหตุโจรสลัด"],
    ["Are the watertight doors closed?", "SMCP asking if secure compartments are sealed.", "Are the watertight doors closed?", "ประตูกันน้ำปิดหรือยัง", "ถามว่าประตูกันน้ำปิดไหม"],
    ["The watertight doors are closed", "SMCP stating secure compartments are sealed.", "The watertight doors are closed.", "ประตูกันน้ำปิดแล้ว", "แจ้งว่าประตูกันน้ำปิดแล้ว"],
    ["Switch on the radar", "SMCP command to activate radar.", "Switch on the radar.", "เปิดเรดาร์", "สั่งให้เปิดเรดาร์"],
    ["Change to VHF channel", "SMCP command to switch radio frequency.", "Change to VHF channel 16.", "เปลี่ยนไปใช้ช่อง VHF", "สั่งเปลี่ยนช่องวิทยุ"],
    ["I am changing to VHF channel", "SMCP stating radio frequency switch.", "I am changing to VHF channel 12.", "ฉันกำลังเปลี่ยนไปใช้ช่อง VHF", "แจ้งเปลี่ยนช่องวิทยุ"],
    ["Message not understood", "SMCP stating lack of comprehension.", "Message not understood.", "ไม่เข้าใจข้อความ", "แจ้งว่าฟังไม่เข้าใจ"]
  ];

  standardPhrases.forEach(p => {
    generatedVocab.push({ term: p[0], definition: p[1], example: p[2], category: "Communication", thai_translation: p[3], thai_meaning: p[4], level: "Officer Level" });
  });

  // 3. Combinatorial Communication Phrases (7 actions x 30 equipments = 210 items)
  const actions = [
    { verb: "Check the", def: "To inspect or verify the status of", thaiVerb: "ตรวจสอบ", thaiDef: "ตรวจสอบสถานะของ" },
    { verb: "Start the", def: "To initiate the operation of", thaiVerb: "เริ่มการทำงานของ", thaiDef: "เปิดเครื่องหรือระบบ" },
    { verb: "Stop the", def: "To halt the operation of", thaiVerb: "หยุดการทำงานของ", thaiDef: "ปิดเครื่องหรือระบบ" },
    { verb: "Secure the", def: "To make safe or fasten", thaiVerb: "ยึดและจัดเก็บ", thaiDef: "ยึดหรือจัดเก็บให้ปลอดภัยสำหรับ" },
    { verb: "Report status of the", def: "To provide an update on", thaiVerb: "รายงานสถานะของ", thaiDef: "แจ้งสถานะปัจจุบันของ" },
    { verb: "Maintain watch on the", def: "To keep continuous observation of", thaiVerb: "เฝ้าระวัง", thaiDef: "เฝ้าสังเกตการณ์อย่างต่อเนื่องสำหรับ" },
    { verb: "Test the", def: "To perform a trial run or diagnostic on", thaiVerb: "ทดสอบ", thaiDef: "ทำการทดลองหรือวิเคราะห์การทำงานของ" }
  ];

  const equipments = [
    { name: "Main Engine", thai: "เครื่องจักรใหญ่" }, { name: "Auxiliary Generator", thai: "เครื่องปั่นไฟสำรอง" }, { name: "Steering Gear", thai: "เครื่องหางเสือ" },
    { name: "Ballast Pump", thai: "ปั๊มน้ำถ่วงเรือ" }, { name: "Fire Pump", thai: "ปั๊มน้ำดับเพลิง" }, { name: "Radar", thai: "เรดาร์" },
    { name: "ECDIS", thai: "ระบบแผนที่อิเล็กทรอนิกส์" }, { name: "VHF Radio", thai: "วิทยุ VHF" }, { name: "Mooring Lines", thai: "เชือกผูกเรือ" },
    { name: "Anchor Windlass", thai: "กว้านสมอเรือ" }, { name: "Cargo Crane", thai: "ปั้นจั่นสินค้า" }, { name: "Hatch Covers", thai: "ฝาระวางสินค้า" },
    { name: "Lifeboat", thai: "เรือชูชีพ" }, { name: "Gangway", thai: "สะพานเดินเรือ" }, { name: "Oily Water Separator", thai: "เครื่องแยกน้ำมัน" },
    { name: "Boiler", thai: "หม้อต้มไอน้ำ" }, { name: "Fuel Purifier", thai: "เครื่องกรองน้ำมัน" }, { name: "Air Compressor", thai: "เครื่องอัดอากาศ" },
    { name: "Fresh Water Generator", thai: "เครื่องผลิตน้ำจืด" }, { name: "Incinerator", thai: "เตาเผาขยะ" }, { name: "Bow Thruster", thai: "ใบพัดหัวเรือ" },
    { name: "Magnetic Compass", thai: "เข็มทิศแม่เหล็ก" }, { name: "Echo Sounder", thai: "เครื่องหยั่งน้ำ" }, { name: "Navtex", thai: "ระบบรับข่าวสารการเดินเรือ" },
    { name: "GMDSS Console", thai: "ชุดคอนโซล GMDSS" }, { name: "Bilge Alarm", thai: "สัญญาณเตือนน้ำท้องเรือ" }, { name: "Fire Alarm Panel", thai: "แผงควบคุมสัญญาณแจ้งไฟไหม้" },
    { name: "CO2 System", thai: "ระบบดับเพลิง CO2" }, { name: "Emergency Generator", thai: "เครื่องปั่นไฟฉุกเฉิน" }, { name: "Cargo Manifold", thai: "ท่อรวมสินค้า" }
  ];

  actions.forEach(action => {
    equipments.forEach(eq => {
      generatedVocab.push({
        term: `${action.verb} ${eq.name}`,
        definition: `${action.def} the ${eq.name.toLowerCase()}.`,
        example: `Please ${action.verb.toLowerCase()} ${eq.name.toLowerCase()} immediately.`,
        category: "Communication",
        thai_translation: `${action.thaiVerb}${eq.thai}`,
        thai_meaning: `${action.thaiDef}${eq.thai}`,
        level: "Cadet Level"
      });
    });
  });

  // Merge and Filter duplicates
  const existingTerms = new Set(vocab.map(v => v.term.toLowerCase()));
  let addedCount = 0;

  generatedVocab.forEach(item => {
    if (addedCount < 1000 && !existingTerms.has(item.term.toLowerCase())) {
      vocab.push(item);
      addedCount++;
    }
  });

  // Write back to JSON
  fs.writeFileSync(vocabFilePath, JSON.stringify(vocab, null, 2), 'utf8');
  console.log(`Successfully added ${addedCount} phrases. Total vocabulary is now ${vocab.length}.`);
}

expandVocabulary();